# Insert Additional Values Here
version: main.659
imagePrefix: eu.gcr.io/gitpod-core-dev/build/
components:
  wsDaemon:
    containerRuntime:
      nodeRoots:
        - /var/lib
        - /run/containerd/io.containerd.runtime.v1.linux/moby
rabbitmq:
  # ensure shovels are configured on boot
  shovels:
    - name: messagebus-0
      srcUri: "amqp://$USERNAME:$PASSWORD@messagebus-0"
  auth:
    username: override-me
    password: override-me