# Insert Additional Values Here
version: main.691
imagePrefix: eu.gcr.io/gitpod-core-dev/build/
installation:
  region: ap-southeast-1
components:
  contentService:
    remoteStorage:
      minio:
        region: ap-southeast-1
  wsDaemon:
    containerRuntime:
      nodeRoots:
        - /var/lib
        - /run/containerd/io.containerd.runtime.v1.linux/moby
      userNamespaces:
        shiftfsModuleLoader:
          enabled: true
rabbitmq:
  # ensure shovels are configured on boot
  shovels:
    - name: messagebus-0
      srcUri: "amqp://$USERNAME:$PASSWORD@messagebus-0"
  auth:
    username: override-me
    password: override-me
