# Insert Additional Values Here
version: main.691
imagePrefix: eu.gcr.io/gitpod-core-dev/build/
installation:
  region: ap-southeast-1
imagePullPolicy: Always
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gitpod.io/workload_meta
          operator: In
          values:
          - "true"
components:
  wsScheduler:
    scaler:
      enabled: false
      controller:
        kind: "constant"
        constant:
          setpoint: 1
  workspace:
    affinity:
      default: "gitpod.io/workload_workspace"
  contentService:
    remoteStorage:
      blobQuota: 6073741824 # 6 GiB
      minio:
        region: ap-southeast-1
  wsDaemon:
    workspaceSizeLimit: "5g"
    containerRuntime:
      nodeRoots:
        - /var/lib
        - /run/containerd/io.containerd.runtime.v1.linux/moby
    userNamespaces:
      shiftfsModuleLoader:
        enabled: true
rabbitmq:
  # ensure shovels are configured on boot
  shovels:
    - name: messagebus-0
      srcUri: "amqp://$USERNAME:$PASSWORD@messagebus-0"
  auth:
    username: override-me
    password: override-me
